#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	/* thêm các collisionType khác trong tool vào đây */
	COLLISION_TYPE_PLAYER,
	COLLISION_TYPE_WATER,
	COLLISION_TYPE_WATER_SURFACE,
	COLLISION_TYPE_WEAPON_PLAYER,
	COLLISION_TYPE_GATE,
	COLLISION_TYPE_WEAPON,
	
	/* số lượng collisionType luôn nằm cuối */
	COLLISION_TYPE_COUNT
};
